# Generated by Django 4.0.6 on 2022-07-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='lea-232-black-lotus.jpeg', upload_to='', verbose_name='Картинка'),
        ),
    ]
